//
// Created by anvar on 27/12/19.
//

#ifndef SILICON_EXCEPTIONCODES_H
#define SILICON_EXCEPTIONCODES_H

namespace sc
{
#define EXCEPTION_SOCKET_CREATION_FAILED    0x0001
#define EXCEPTION_SOCKET_BINDING_FAILED     0x0002
#define EXCEPTION_PORT_NO_IN_USE            0x0003
#define EXCEPTION_SOCKET_LISTEN_FAILED      0x0004
#define EXCEPTION_SOCKET_ACCEPT_FAILED      0x0005
#define EXCEPTION_SOCKET_READ_FAILED        0x0006
}

#endif //SILICON_EXCEPTIONCODES_H
